#!/bin/bash
# Ruff linting and formatting script

echo "=== Ruff Configuration and Usage Guide ==="
echo ""
echo "1. Check code for linting issues:"
echo "   ruff check ."
echo ""
echo "2. Check specific directory:"
echo "   ruff check backend/"
echo ""
echo "3. See all violations with detailed output:"
echo "   ruff check . --show-fixes"
echo ""
echo "4. Format code automatically:"
echo "   ruff format ."
echo ""
echo "5. Fix auto-fixable violations:"
echo "   ruff check . --fix"
echo ""
echo "6. Format and fix in one command:"
echo "   ruff format . && ruff check . --fix"
echo ""
echo "=== Configuration Files ==="
echo "- pyproject.toml: Main Ruff configuration"
echo "- .ruff.toml: Alternative TOML configuration file"
echo ""
echo "=== Current Ruff Version ==="
ruff --version
echo ""
echo "=== Configuration Summary ==="
echo "- Line length: 120 characters"
echo "- Target Python: 3.11+"
echo "- Enabled rules: E, W, F, I, N, UP, B"
echo "- Quote style: Double quotes"
echo "- Django-aware: Yes (agora_backend and core are marked as first-party)"
