"""
Django settings for agora_backend project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# === Base Paths ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Environment Variables ===
load_dotenv()
SECRET_KEY = os.getenv("SECRET_KEY", "dev-only-insecure-secret-key")
DEBUG = os.getenv("DEBUG", "True") == "True"
ALLOWED_HOSTS = ["127.0.0.1", "localhost", "testserver"]

# === Installed Apps ===
INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'core.apps.CoreConfig',

    # Yale CAS (NetID Login)
    'django_cas_ng',
]

# === Middleware ===
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agora_backend.urls'

# === Templates ===
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'agora_backend' / 'templates'],  # settings_local.py 会自动追加你的 agora_frontend/templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agora_backend.wsgi.application'

# === Database ===
# Use SQLite by default (no setup needed!)
# To use PostgreSQL, set environment variable: export USE_POSTGRESQL=True

if os.getenv('USE_POSTGRESQL', 'False') == 'True':
    # PostgreSQL (production)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'agora_db',
            'USER': 'agora_user',
            'PASSWORD': 'password123',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }
else:
    # SQLite (development - no setup needed!)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# === Password Validation ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === Internationalization ===
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# === Email Configuration ===
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@agora.yale.edu')

# === Site Configuration ===
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')

# === Static Files ===
STATIC_URL = 'static/'

# === Default Primary Key ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === Custom User Model ===
AUTH_USER_MODEL = "core.CustomUser"

# === Authentication Backends ===
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'django_cas_ng.backends.CASBackend',
]

# === CAS (Yale NetID Login) Settings ===
CAS_SERVER_URL = 'https://secure.its.yale.edu/cas/'
CAS_VERSION = '3'
CAS_LOGOUT_COMPLETELY = True
CAS_REDIRECT_URL = '/'
CAS_LOGIN_MSG = None
CAS_LOGOUT_MSG = None

# === Login/Logout URLs ===
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/'

