"""
Django settings for agora_backend project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# === Base Paths ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Environment Variables ===
load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY") or 'django-insecure-dev-placeholder'
# Robust DEBUG parsing: treat any case-insensitive 'true' as True
DEBUG = os.getenv("DEBUG", "True").strip().lower() == "true"
# Parse and strip ALLOWED_HOSTS; ignore empties and whitespace-only entries
_raw_allowed_hosts = os.getenv(
    "ALLOWED_HOSTS",
    "agora-backend-vavf.onrender.com,127.0.0.1,localhost,.onrender.com"
)
ALLOWED_HOSTS = [h.strip() for h in _raw_allowed_hosts.split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# Allow explicit wildcard override for troubleshooting (DO NOT use long-term)
if os.getenv("ALLOW_ALL_HOSTS", "False").strip().lower() == "true":
    ALLOWED_HOSTS = ["*"]

print(f"[startup] DEBUG={DEBUG} ALLOWED_HOSTS={ALLOWED_HOSTS}")
# Auto-append Render external URL host if missing (helps avoid DisallowedHost when env var mis-set)
_render_external = os.getenv("RENDER_EXTERNAL_URL")
if _render_external:
    _render_host = _render_external.split('://')[-1].strip('/')
    if _render_host and _render_host not in ALLOWED_HOSTS and '*' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_render_host)
        print(f"[startup] Added render host '{_render_host}' to ALLOWED_HOSTS -> {ALLOWED_HOSTS}")


# Application definition

INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'backend.core.apps.CoreConfig',

    # Yale CAS (NetID Login)
    'django_cas_ng',
]

# === Middleware ===
MIDDLEWARE = [
    'agora_backend.middleware.ExceptionLoggingMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Exempt API endpoints from CSRF (DRF handles authentication separately)
CSRF_COOKIE_SECURE = not DEBUG  # Only send CSRF cookie over HTTPS in production
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF cookie
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'None' if not DEBUG else 'Lax'

# CORS settings
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'agora_backend.urls'

# === Templates ===
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'agora_backend' / 'templates'],  # settings_local.py 会自动追加你的 agora_frontend/templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agora_backend.wsgi.application'

# === Database ===
# Use SQLite by default (no setup needed!)
# To use PostgreSQL, set environment variable: export USE_POSTGRESQL=True

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use DATABASE_URL from Render if available, otherwise use local settings
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', 'postgresql://agora_user:password123@localhost:5432/agora_db'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# === Password Validation ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === Internationalization ===
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# === Email Configuration ===
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@agora.yale.edu')

# === Site Configuration ===
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media (user-uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# === Default Primary Key ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === Custom User Model ===
AUTH_USER_MODEL = "core.CustomUser"

# Auth redirects
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/profile/'

# CORS settings - support both local and production
# Strip whitespace and filter out empty strings
cors_origins = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://10.0.0.111:3000,https://*.onrender.com"
)
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins.split(",") if origin.strip()]

# CSRF settings - support both local and production
csrf_origins = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:3000,http://10.0.0.111:3000,https://*.onrender.com"
)
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins.split(",") if origin.strip()]

# Allow all origins in development if DEBUG is True (for testing)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# Session cookie settings for production (cross-origin authentication)
SESSION_COOKIE_SAMESITE = 'None' if not DEBUG else 'Lax'
SESSION_COOKIE_SECURE = not DEBUG  # Require HTTPS in production
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_DOMAIN = os.getenv('SESSION_COOKIE_DOMAIN', None)  # Set to your domain in production
