# Generated by Django 5.2.8 on 2025-12-01 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_initial_circles"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="circlemembership",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="circle",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="circle",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_circles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circle",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="circle",
            name="members",
            field=models.ManyToManyField(
                related_name="joined_circles",
                through="core.CircleMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("creator", "Creator"),
                    ("admin", "Admin"),
                    ("member", "Member"),
                    ("pending", "Pending Approval"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="circle",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="circlemembership",
            name="circle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="core.circle",
            ),
        ),
        migrations.AlterField(
            model_name="circlemembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circle_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="circlemembership",
            unique_together={("circle", "user")},
        ),
    ]
