# Generated by Django 5.2.8 on 2025-12-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_circlemembership_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circle",
            name="created_at",
        ),
    ]
