# Generated by Django 5.2.8 on 2025-11-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="grade",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Grade/Year"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="program",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Major/Program"
            ),
        ),
    ]
