# Generated by Django 5.2.8 on 2025-11-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_fix_avatar_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="netid",
            field=models.CharField(blank=True, default="", max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="school",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="year",
            field=models.CharField(default="", max_length=10),
        ),
    ]
